# Generated by Django 5.2.1 on 2025-05-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictaphone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='UPLOADS'),
        ),
    ]
