# Generated by Django 5.2.1 on 2025-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictaphone', '0002_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestIdJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255)),
            ],
        ),
    ]
