# Generated by Django 5.2.1 on 2025-06-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictaphone', '0004_silencethreshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='UPLOADS/INPUT'),
        ),
    ]
