# Generated by Django 5.2.1 on 2025-06-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictaphone', '0005_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingFilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
            ],
        ),
    ]
